const state={files:[],records:[],headers:[],output:null};
const $=id=>document.getElementById(id);
function norm(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function findCol(headers,names){const wanted=names.map(norm);return headers.findIndex(h=>wanted.includes(norm(h)))}
function setProgress(n,text){$('progressBar').style.width=`${n}%`;$('progressText').textContent=text}
function cellValue(v){if(v==null)return '';if(typeof v==='object'&&v.result!=null)return v.result;return String(v)}
async function readFile(file){const wb=new ExcelJS.Workbook();const buf=await file.arrayBuffer();await wb.xlsx.load(buf);let records=[];let headers=[];wb.eachSheet(ws=>{if(!headers.length){const r=ws.getRow(1);headers=r.values.slice(1).map(v=>cellValue(v));}for(let r=2;r<=ws.rowCount;r++){const row=ws.getRow(r);const vals=row.values.slice(1);if(vals.some(v=>cellValue(v).trim()!=='')){records.push({values:headers.map((_,i)=>cellValue(vals[i]??'')),source:file.name,sheet:ws.name});}}});return {name:file.name,rows:records.length,records,headers};}
function renderFiles(){const box=$('fileList');box.innerHTML=state.files.map(f=>`<div class="file-row"><div class="file-name">${escapeHtml(f.name)}</div><div class="file-meta">${f.rows} registros</div></div>`).join('');box.classList.toggle('hidden',!state.files.length);$('fileCount').textContent=state.files.length;$('rowCount').textContent=state.records.length;$('statusPill').textContent=state.files.length?`${state.files.length} archivo${state.files.length===1?'':'s'}`:'Sin archivos';$('statusPill').classList.toggle('ready',!!state.files.length);$('exportBtn').disabled=!state.records.length;}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('fileInput').addEventListener('change',async e=>{state.files=[];state.records=[];state.headers=[];$('loadError').classList.add('hidden');try{for(const file of e.target.files){const r=await readFile(file);if(!state.headers.length)state.headers=r.headers;state.files.push({name:r.name,rows:r.rows});state.records.push(...r.records)}renderFiles();}catch(err){console.error(err);$('loadError').textContent='No se pudo leer el archivo Excel: '+(err.message||err);$('loadError').classList.remove('hidden');state.files=[];state.records=[];renderFiles();}});
function barcodeDataUrl(value){const c=document.createElement('canvas');c.width=285;c.height=40;JsBarcode(c,String(value),{format:'CODE128',width:1.45,height:32,margin:0,displayValue:false,lineColor:'#000000'});return c.toDataURL('image/png');}
async function buildWorkbook(){const wb=new ExcelJS.Workbook();const ws=wb.addWorksheet('Datos');const headers=[...state.headers,'Código de barras'];ws.addRow(headers);ws.autoFilter={from:1,to:headers.length,fromRow:1,toRow:Math.max(1,state.records.length+1)};const chasisCol=findCol(state.headers,['chasis','chassis']);if(chasisCol<0)throw new Error('No se encontró una columna "Chasis".');const barcodeCol=headers.length;ws.getColumn(barcodeCol).width=38.0;ws.getRow(1).height=22;ws.getRow(1).font={bold:true};for(let i=0;i<state.records.length;i++){const rec=state.records[i];const row=ws.addRow([...rec.values,'']);row.height=30;const chasis=rec.values[chasisCol]||'';if(chasis){const data=barcodeDataUrl(chasis);const imageId=wb.addImage({base64:data,extension:'png'});ws.addImage(imageId,{tl:{col:barcodeCol-1,row:i+1},br:{col:barcodeCol,row:i+2}});}setProgress(Math.round((i+1)/state.records.length*100),`Generando código ${i+1} de ${state.records.length}`);await new Promise(r=>setTimeout(r,0));}return wb;}
$('exportBtn').addEventListener('click',async()=>{try{$('exportBtn').disabled=true;$('progressArea').classList.remove('hidden');$('resultBox').classList.add('hidden');setProgress(5,'Preparando Excel...');state.output=await buildWorkbook();const buf=await state.output.xlsx.writeBuffer();state.outputBytes=buf;setProgress(100,'Listo');$('resultText').textContent=`${state.records.length} registros preparados. El archivo XLSX incluye los códigos de barras.`;$('resultBox').classList.remove('hidden');}catch(err){console.error(err);$('loadError').textContent='No se pudo generar el Excel: '+(err.message||err);$('loadError').classList.remove('hidden');}finally{$('exportBtn').disabled=false;}});
$('downloadBtn').addEventListener('click',()=>{if(!state.outputBytes)return;const blob=new Blob([state.outputBytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='excel_unificado_v1.2.0.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
